### PR TITLE
Mojo team suggestions for shared infrastructure

### PR DESCRIPTION
**Pull request by ArdenIvanov**

### CODE REVIEW

**Comment by ArdenIvanov** [comment]
Our main suggestion points:

- Having flexible base webpack configuration
- Support for view.json file with particular page configuration
- Support for language terms to be used like "$$lang"
- Support for context items to be used like "$$context"
- Support for using SASS inside Svelte files using pre-processor
- Support for generating cshtml file and model file for an entry point

**Comment by furstenberg** [comment]
So could you tell me more about this flexible base webpack configuration?

- Is this meant as a replacement for the existing `webpack.config.js`?
- If we replace the current with this new one, will existing repos that use the current config break if they upgrade?
- This package is public and can be used outside itslearning. Will these changes affect project outside of itslearning?

**Comment by ArdenIvanov** [comment]
Originally it was meant as an option to choose for developers - use standard `webpack.config.js` or this one. But maybe it is better to increase major version and leave only this one with guide on how to migrate.
And yes, it is not backwards compatible with the current one, so existing repos can't be easily upgraded.
Not sure about usages outside of itslearning, but I am sure that we can provide a good guide on the upgrade.

**Comment by plumpNation** [comment]
It looks as though the line endings have changed. Is there a reason for that?

**Comment by ArdenIvanov** [comment]
No, line ending change is not intentional, I think this happened because one of developers has incorrect git settings

**Comment by furstenberg** [comment]
"so existing repos can't be easily upgraded."

That is a line I don't like to read.  How would you propose to get buy in from stakeholders for upgrading all existing stuff? That line alone make me want to just close this MR. 

- Having flexible base webpack configuration

This implies that the current configuration isn't flexible. I would disagree with that. It's just as strict as it need to be. But perhaps you could  describe what makes this new configuration flexible or at least what makes the current one *not* flexible?

- Support for view.json file with particular page configuration

Could you explain what a view.json file is and why it is beneficial? Does it belong in this tool? Remember that this a tool also used outside of the scope of itslearning.

- Support for language terms to be used like "$$lang"

With Svelte v3 adopting "$:" in the "language" it seems unwise to introduce such a similar construct at this time. I would rethink the use of the "$$". (If you look at the code the compiler outputs it also uses $$.) But a plugin adding support for this might work. Should be a separate PR though.

- Support for context items to be used like "$$context"

See comment above regarding the use of "$$". Then explain to me what a context item is and what benefit it will bring to this repo.

- Support for using SASS inside Svelte files using pre-processor

As previously mentioned our current system for generating both AA and AAA scss files would be difficult to do with SCSS in Svelte files. I think a separate PR for adding support for SCSS in Svelte makes more sense than having it be part of this.

- Support for generating cshtml file and model file for an entry point

As previously mentioned this might be a fine plugin, but I'm not sure that having a plugin handling cshtml makes sense in this repo. I think a separate repo for plugins would make more sense or perhaps we should add a /plugins folder? Again something that should be part of a separate PR.

**Comment by furstenberg** [comment]
Closing this since it’s being moved elsewhere.

**Pull request closed without merging**
